// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: music_player

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

void play_pause_button_cb(lv_event_t * event);
void next_button_cb(lv_event_t * event);
#endif
